MSG_PROCESSING = 'Processing'
MSG_SERVICE_UNAVAILABLE = 'Service Unavailable'

CODE_DONE = 1000
CODE_PROCESSING = 1001
CODE_URL_UNAVAILABLE = 1002
CODE_SERVICE_UNAVAILABLE = 1003
CODE_ADDRESS_NOT_EXIST = 1004
CODE_ADDRESS_ALREADY_EXIST = 1005
CODE_FAIL = 1008

MONGO_DATABASE='address'
MONGO_ADMIN_USER='admin'
MONGO_ADMIN_PWD='admin'
MONGO_HOSTNAME='localhost'
FLASK_ENV='development'